import type { Config } from 'tailwindcss';

const config: Config = {
  content: ['./src/**/*.{js,ts,jsx,tsx,mdx}'],
  theme: {
    extend: {
      colors: {
        surface: '#fcf9f8',
        'surface-dim': '#dcd9d9',
        'surface-bright': '#fcf9f8',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f6f3f2',
        'surface-container': '#f0eded',
        'surface-container-high': '#eae7e7',
        'surface-container-highest': '#e5e2e1',
        'on-surface': '#1c1b1b',
        'on-surface-variant': '#4f4633',
        'inverse-surface': '#313030',
        'inverse-on-surface': '#f3f0ef',
        outline: '#817660',
        'outline-variant': '#d3c5ac',
        'surface-tint': '#785900',
        primary: '#785900',
        'on-primary': '#ffffff',
        'primary-container': '#f2b705',
        'on-primary-container': '#644a00',
        'inverse-primary': '#f9bd14',
        secondary: '#a53c00',
        'on-secondary': '#ffffff',
        'secondary-container': '#fd6b25',
        'on-secondary-container': '#5a1d00',
        tertiary: '#645e51',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#c8bfb0',
        'on-tertiary-container': '#534e42',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'primary-fixed': '#ffdf9d',
        'primary-fixed-dim': '#f9bd14',
        'on-primary-fixed': '#251a00',
        'on-primary-fixed-variant': '#5b4300',
        'secondary-fixed': '#ffdbce',
        'secondary-fixed-dim': '#ffb598',
        'on-secondary-fixed': '#370e00',
        'on-secondary-fixed-variant': '#7e2c00',
        'tertiary-fixed': '#ebe1d1',
        'tertiary-fixed-dim': '#cfc5b6',
        'on-tertiary-fixed': '#1f1b11',
        'on-tertiary-fixed-variant': '#4c463b',
        background: '#fcf9f8',
        'on-background': '#1c1b1b',
        'surface-variant': '#e5e2e1',
      },
      fontFamily: {
        display: ['"Be Vietnam Pro"', 'sans-serif'],
        body: ['"Be Vietnam Pro"', 'sans-serif'],
        label: ['"Work Sans"', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['56px', { lineHeight: '64px', letterSpacing: '-0.02em', fontWeight: '800' }],
        'display-lg-mobile': ['40px', { lineHeight: '48px', letterSpacing: '-0.02em', fontWeight: '800' }],
        'headline-md': ['32px', { lineHeight: '40px', fontWeight: '700' }],
        'headline-sm': ['24px', { lineHeight: '32px', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-bold': ['14px', { lineHeight: '20px', letterSpacing: '0.05em', fontWeight: '600' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '500' }],
      },
      borderRadius: {
        sm: '0.25rem',
        DEFAULT: '0.5rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
      },
      spacing: {
        base: '8px',
        'container-max': '1280px',
        gutter: '24px',
        'margin-desktop': '64px',
        'margin-mobile': '20px',
        'stack-sm': '12px',
        'stack-md': '24px',
        'stack-lg': '48px',
      },
      maxWidth: {
        'container-max': '1280px',
      },
    },
  },
  plugins: [],
};

export default config;
